### ISSUE TITLE
Cannot install bitcoinfiles-sdk from npm

### ISSUE THREAD

**Issue by jdh7190** [BitcoinFiles/bitcoinfiles-sdk#6]
I receive the following when trying to install the bitcoinfiles-sdk package on Windows via npm:

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Bitcoin-com/bip21.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jhens\AppData\Roaming\npm-cache\_logs\2020-04-23T03_28_26_963Z-debug.log

Actually the issue appears to be referencing old packages and not being able to find git files:

npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Bitcoin-com/bip21.git

I notice lots of packages referenced when installing via NPM are outdated, this is likely related to the issue.

**Comment by ghost** [comment]
Updated deps. Please try again.

update: `npm install bitcoinfiles-sdk --save`

**Comment by jdh7190** [comment]
I still receive the same error:

C:\Users\jhens\node\bfiles>npm install bitcoinfiles-sdk --save
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Bitcoin-com/bip21.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jhens\AppData\Roaming\npm-cache\_logs\2020-05-07T05_08_15_229Z-debug.log

**Comment by ghost** [comment]
Checking...

Please ensure you are using node version 10.x +

I've removed a number of deps now and it's lighter weight. Can you please try to fetch latest from npm and see if it resolved issue? V 2.3.0

`sudo npm install --unsafe-perm=true` 

(You might need unsafe-perm if you get permission errors)

**Comment by jdh7190** [comment]
I was able to install - thank you so much!!
